-- phpMyAdmin SQL Dump
-- version 4.3.8
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jul 02, 2017 at 09:20 AM
-- Server version: 5.6.32-78.1-log
-- PHP Version: 5.6.20

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `bostonj2_wor1`
--

-- --------------------------------------------------------

--
-- Table structure for table `ghs_gigpress_shows`
--

CREATE TABLE IF NOT EXISTS `ghs_gigpress_shows` (
  `show_id` int(4) NOT NULL,
  `show_artist_id` int(4) NOT NULL,
  `show_venue_id` int(4) NOT NULL,
  `show_tour_id` int(4) DEFAULT '0',
  `show_date` date NOT NULL,
  `show_multi` int(1) DEFAULT NULL,
  `show_time` time NOT NULL,
  `show_expire` date NOT NULL,
  `show_price` varchar(255) DEFAULT NULL,
  `show_tix_url` varchar(255) DEFAULT NULL,
  `show_tix_phone` varchar(255) DEFAULT NULL,
  `show_ages` varchar(255) DEFAULT NULL,
  `show_notes` text,
  `show_related` bigint(20) DEFAULT '0',
  `show_status` varchar(32) DEFAULT 'active',
  `show_external_url` varchar(255) DEFAULT NULL,
  `show_tour_restore` int(1) DEFAULT '0',
  `show_address` varchar(255) DEFAULT NULL,
  `show_locale` varchar(255) DEFAULT NULL,
  `show_country` varchar(2) DEFAULT NULL,
  `show_venue` varchar(255) DEFAULT NULL,
  `show_venue_url` varchar(255) DEFAULT NULL,
  `show_venue_phone` varchar(255) DEFAULT NULL
) ENGINE=MyISAM AUTO_INCREMENT=74 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `ghs_gigpress_shows`
--

INSERT INTO `ghs_gigpress_shows` VALUES(1, 1, 2, 1, '2014-11-21', 0, '19:30:00', '2014-11-21', '', 'https://www.vendini.com/ticket-software.html?t=tix&amp;e=eda6709ed960061ffb6d0fa22eed1ce7', '', '', 'The prophecies, tribulations, and triumph of the young Biblical hero Daniel, as retold in music from medieval Beauvais. Probably the most powerful and musically evocative of all the medieval mystery plays, in a splendid new production conceived by Anne Azéma. A translation of the play can be <a href="/programs//DanielTranslation.html">viewed here</a> and <a href="/download/DanielTranslation.pdf">downloaded here</a>.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(5, 1, 2, 1, '2014-11-23', 0, '15:00:00', '2014-11-23', '', 'https://www.vendini.com/ticket-software.html?t=tix&amp;e=eda6709ed960061ffb6d0fa22eed1ce7', '', '', 'The prophecies, tribulations, and triumph of the young Biblical hero Daniel, as retold in music from medieval Beauvais. Probably the most powerful and musically evocative of all the medieval mystery plays, in a splendid new production conceived by Anne Azéma. A translation of the play can be <a href="/programs/DanielTranslation.html">viewed here</a> and <a href="/download/DanielTranslation.pdf">downloaded here</a>.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(2, 2, 1, 1, '2014-12-20', 0, '20:00:00', '2014-12-20', '', 'http://www.vendini.com/ticket-software.html?t=tix&amp;e=a02cbd8242a1077e03dcde2fa4bc6cbc', '', '', '', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(8, 3, 7, 2, '2015-03-01', 0, '13:00:00', '2015-03-01', '', 'http://www.metmuseum.org/events/programs/concerts-and-performances/the-boston-camerata-a?eid=37235', '', '', 'Close to Reims, the regions of Champagne, Picardy, and Lorraine brought forth an abundant harvest of song in French, both secular and sacred.  The subject of “Heaven''s Gate” is the magnificent repertoire, composed in both the courtly and popularizing manners, in praise of the Virgin Mary.  Noble songs in the refined trouvère style, narrations in word and song, and dance music with sacred texts, are all included in this production. The prior of Vic-sur-Aisne, Gauthier de Coincy (1177/8-1236), a passionate and prolix musician-poet, recounts the miracles of the Virgin that took place in his parish; Thibault de Champagne (1201-1253), count of Champagne and king of Navarra, praises the Queen of Heaven in the most elegant and subtle style; while anonymous minstrels transform the worldly songs of the day into vigorous, toe-tapping spirituals.', 0, 'soldout', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(9, 3, 7, 2, '2015-03-01', 0, '15:00:00', '2015-03-01', '', 'http://www.metmuseum.org/events/programs/concerts-and-performances/the-boston-camerata-b?eid=22657', '', '', '', 0, 'soldout', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(3, 2, 3, 2, '2014-12-13', 0, '19:30:00', '2014-12-13', '', '', '', '', 'To celebrate our 60th Anniversary, our Christmas program features music from our very own tradition. From the early years of the American republic, and from a wide range of early tune books and manuscripts, a generous selection of carols, New England anthems, Southern folk hymns and religious ballads for the season.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(4, 2, 4, 2, '2014-12-21', 0, '15:00:00', '2014-12-21', '', 'http://unioncollegeconcerts.org/?product=boston-camerata122114', '', '', '', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(6, 2, 5, 1, '2014-12-19', 0, '20:00:00', '2014-12-19', '', 'http://www.vendini.com/ticket-software.html?t=tix&amp;e=83cec4686b3761e60ae4981512bc7765', '', '', '', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(7, 2, 6, 1, '2014-12-18', 0, '20:00:00', '2014-12-18', '', 'http://www.vendini.com/ticket-software.html?t=tix&amp;e=3398f39f907a12bce135b2bb74347b64', '', '', '', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(10, 4, 8, 2, '2014-12-07', 1, '17:00:00', '2014-12-07', '', '', '', '', '', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(11, 5, 9, 1, '2015-03-06', 0, '20:00:00', '2015-03-06', '', 'http://www.vendini.com/ticket-software.html?t=tix&amp;e=3464f077eac24824607a75183e523a3e', '', '', 'The constantly evolving and inventive musical minds of Italian and French masters during the fourteenth century has left us with repertoires, both sacred and secular, that successfully unite the search for new and different creative paths with astonishing lyricism and sensual beauty. In this specially commissioned program for the Massachusetts Institute of Technology, you will hear music spanning the worlds of God and Man, by the greatest composers of their day: Machaut, Landini, da Bologna, and others, performed by Camerata''s virtuoso soloists and instrumentalists.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(12, 6, 10, 2, '2015-03-28', 0, '16:00:00', '2015-03-28', '', 'http://portlandovations.org/shows/boston-camerata.shtml', '', '', 'Back by popular demand! An interfaith celebration unlike any other. Discover with us the common musical roots of Judaism, Islam, and Christianity, and the astonishing and beautiful interactions among these traditions. Our program includes elements of Jewish liturgy, Gregorian and Koranic chant, songs and texts of Jewish minstrels, Sephardic folksong, medieval Spanish Cantigas, and Judaeo-Islamic music from the ancient Andalusian tradition. The Boston Camerata is joined by Sharq Arabic Music Ensemble.\r\nConcert runtime 1 hour 45 min', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(13, 6, 11, 2, '2015-03-29', 0, '15:00:00', '2015-03-29', '', 'http://www.vendini.com/ticket-software.html?t=tix&amp;e=3dd91022e70b96ef13e3c1b9bed25984', '', '', 'Concert runtime: 1 hour 45 min', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(14, 7, 12, 2, '2015-04-11', 0, '15:00:00', '2015-04-11', '', 'http://www.theatredelaville-paris.com/spectacle-bostoncamerataanneazema-814', '', '', 'Drawing on the original 13th-century manuscript, The Boston Camerata’s Carmina Burana presents a panoramic portrait of student and clerical life in medieval Europe: paeans to the Goddess Fortune, funny and ferocious critiques of Church and State, earnest meditations on truth and righteousness, and a generous serving of songs about drinking, gambling and amorous adventure. With its usual verve and vivacity, the Camerata gives a deepened, in turn exuberant and contemplative reading of this manuscript, under the direction of vocalist Anne Azéma. Our stellar cast (Anne Azéma, Joel Frederiksen, Tim Evans, voice; Shira Kammen and Susanne Ansorg, strings) will be assisted by a conservatory student choir from Paris.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(15, 7, 17, 2, '2015-04-12', 0, '16:00:00', '2015-04-12', '', '', '', '', '', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(16, 8, 21, 2, '2015-05-09', 0, '19:30:00', '2015-05-09', '', 'http://www.capesymphony.org/cape-symphony-orchestra-concert-9.asp', '', '', 'As a prelude to Carl Orff’s extravagant Carmina Burana, Boston Camerata presents a vivacious portrait of student and clerical life in medieval Europe. This joint concert with the Cape Symphony features Anne Azéma, Joel Cohen, Dan Hershey and Taylor Ward.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(17, 8, 21, 2, '2015-05-10', 0, '15:00:00', '2015-05-10', '', 'http://www.capesymphony.org/cape-symphony-orchestra-concert-9.asp', '', '', '', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(18, 4, 15, 2, '2014-12-06', 0, '19:00:00', '2014-12-06', '', '', '', '', '', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(19, 4, 16, 2, '2014-12-05', 0, '20:30:00', '2014-12-05', '', '', '', '', 'Camerata’s chamber music version of this, our best-known holiday program, features three angelic women’s voices and instrumentalists. Our performance presents magnificent medieval song and poetry from the mid-winter celebration of Christ’s nativity, with a look as well at the pagan celebrations of winter solstice. Countries represented include France, England, Italy, Provence, and Germany.​ This production will include also a distaff choir from Mission Voix Alsace. ​', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(20, 9, 18, 1, '2015-06-17', 0, '19:00:00', '2015-06-17', '', '', '', '', 'concert description....', 0, 'deleted', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(21, 7, 20, 1, '2015-06-05', 0, '19:30:00', '2015-06-05', '$25', 'http://www.nahantmusicfestival.org/tickets-and-passes/', '', '', 'Drawing on the original 13th-century manuscript, The Boston Camerata’s Carmina Burana presents a panoramic portrait of student and clerical life in medieval Europe: paeans to the Goddess Fortune, funny and ferocious critiques of Church and State, earnest meditations on truth and righteousness, and a generous serving of songs about drinking, gambling and amorous adventure. With its usual verve and vivacity, the Camerata gives a deepened, in turn exuberant and contemplative reading of this manuscript, under the direction of vocalist Anne Azéma. Our stellar cast (Anne Azéma, Daniel Hershey, Don Wilkinson, voice; Shira Kammen, strings) is joined by students from the Festival''s apprentice program.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(22, 9, 18, 1, '2015-06-18', 0, '18:00:00', '2015-06-18', '', 'http://www.bostonathenaeum.org/events/2550/patriots-and-heroes-music-young-republic', '', '', 'Who are our heroes? How did they go to battle and with what songs? Whose side were they on?\r\nA medley of early American music featuring a portrait gallery of eminent Americans, but also high spirited celebrations, of the new nation, and around the quintessential American themes of freedom and independence. This program constitutes a chapter in the Boston 2015 celebrations of the Marquis de Lafayette and the historic return of his rebuilt 18th century "freedom frigate", the Hermione.\r\n \r\nDrawing on original print and manuscript sources, we will include songs in celebration of Lafayette''s friends and associates, Washington and Jefferson, as well as both American and French compositions reflecting the social and political climate of the turbulent years 1775-1830. Liberty, martial glory, loyalty, and a healthy dose of satire and irreverence are all present in the lively ballads and broadsides of that crucial time.\r\n\r\nAnne Azéma (director), Camila Parias, Deborah Rentz-Moore, Daniel Hershey, and John Taylor Ward, voices, are joined by Sarah Darling, violin and\r\nLibor Dudas, fortepiano.', 2606, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(23, 10, 22, 1, '2015-10-03', 0, '15:00:00', '2015-10-03', '', 'http://bostoncamerata.org/tickets.html', '', '', 'Latin American Baroque music at its best! This program calls attention to "the meeting places of light and beauty that did indeed exist in those terrible, hard centuries"--the Age of Exploration in the New World. Here we show the fruitful intercultural exchanges that transpired between indigenous American cultures, the Spanish, and the Africans, and indeed, this is beautiful music. Lively and driven at times by the sunny strumming of the baroque guitar and the maracas, tambourine, and claves, at other times stately with the grandeur of voices with organ. The Camerata is joined by the Trinity Choristers, Boston City Singers, and the Haitian women''s choir Les Fleurs des Caraïbes.', 2655, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(24, 10, 2, 1, '2015-10-04', 0, '15:00:00', '2015-10-04', '', 'http://bostoncamerata.org/tickets.html', '', '', 'Latin American Baroque music at its best! This program calls attention to "the meeting places of light and beauty that did indeed exist in those terrible, hard centuries"--the Age of Exploration in the New World. Here we show the fruitful intercultural exchanges that transpired between indigenous American cultures, the Spanish, and the Africans, and indeed, this is beautiful music. Lively and driven at times by the sunny strumming of the baroque guitar and the maracas, tambourine, and claves, at other times stately with the grandeur of voices with organ. The Camerata is joined by the Trinity Choristers, Boston City Singers, and the Haitian women''s choir Les Fleurs des Caraïbes.', 2656, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(25, 11, 5, 1, '2015-12-18', 0, '20:00:00', '2015-12-18', '', 'http://bostoncamerata.org/tickets.html', '', '', 'The Christmas narrative retold using songs, chants, and instrumental pieces from the countries of the Mediterranean basin: Spain, Italy, and southern France, as well as north Africa and the Holy Land.  Works are drawn from medieval manuscripts and more recent, though still archaic, folklore and oral traditions. With voices, early instruments of Europe and the Middle East, and readings of the Christmas story. Camerata is joined by SHARQ Arabic Ensemble.\r\n\r\nAnne Azéma - voice, hurdy-gurdy &amp; director\r\nCamila Parias - voice\r\nDeborah Rentz-Moore - voice\r\nSteven Lundahl - brass, recorder\r\nKarim Nagi - percussion, voice\r\nBoujemaa Ragui - oud, ney, voice, percussion\r\nMehmet Sanlikol - voice, oud\r\nBeth Bahia Cohen - vielle', 2657, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(26, 11, 6, 1, '2015-12-19', 0, '20:00:00', '2015-12-19', '', 'http://bostoncamerata.org/tickets.html', '', '', 'The Christmas narrative retold using songs, chants, and instrumental pieces from the countries of the Mediterranean basin: Spain, Italy, and southern France, as well as north Africa and the Holy Land.  Works are drawn from medieval manuscripts and more recent, though still archaic, folklore and oral traditions. With voices, early instruments of Europe and the Middle East, and readings of the Christmas story. Camerata is joined by SHARQ Arabic Ensemble.\r\n\r\nAnne Azéma - voice, hurdy-gurdy &amp; director\r\nCamila Parias - voice\r\nDeborah Rentz-Moore - voice\r\nSteven Lundahl - brass, recorder\r\nKarim Nagi - percussion, voice\r\nBoujemaa Ragui - oud, ney, voice, percussion\r\nMehmet Sanlikol - voice, oud\r\nBeth Bahia Cohen - vielle', 2658, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(27, 11, 1, 1, '2015-12-21', 0, '20:00:00', '2015-12-21', '', 'http://bostoncamerata.org/tickets.html', '', '', 'The Christmas narrative retold using songs, chants, and instrumental pieces from the countries of the Mediterranean basin: Spain, Italy, and southern France, as well as north Africa and the Holy Land.  Works are drawn from medieval manuscripts and more recent, though still archaic, folklore and oral traditions. With voices, early instruments of Europe and the Middle East, and readings of the Christmas story. Camerata is joined by SHARQ Arabic Ensemble.\r\n\r\nAnne Azéma - voice, hurdy-gurdy &amp; director\r\nCamila Parias - voice\r\nDeborah Rentz-Moore - voice\r\nSteven Lundahl - brass, recorder\r\nKarim Nagi - percussion, voice\r\nBoujemaa Ragui - oud, ney, voice, percussion\r\nMehmet Sanlikol - voice, oud\r\nBeth Bahia Cohen - vielle', 2659, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(28, 12, 11, 1, '2016-04-16', 0, '20:00:00', '2016-04-16', '', 'http://bostoncamerata.org/tickets.html', '', '', 'Another astonishing music-theater production by Artistic Director Anne Azéma. Based on an authentic, colorful narrative of festivity, tournaments, and love games in a medieval French castle, our performance captures the day’s celebrations through song and gesture. Daylight is the domain of men, who joust and fight in ritual encounters, as the women shout encouragement; when night falls, the women converse in music and dance, far from the masculine violence of the daytime. Mutual longing aroused during the day culminates in the evening’s rites, as the sexes come together in courtship, both playful and passionate. Camerata’s musicians are joined by graduate students from the Longy School of Music of Bard College in this beautiful and intense evocation of medieval desire.\r\n\r\nProduced in partnership with Longy School of Music of Bard College.\r\n\r\nPre-concert lecture April 16 at 7pm - Nancy Regalado (NYU). Wolfinsohn Room.', 0, 'active', 'http://bostoncamerata.org/blog/programs/the-nights-tale-a-tournament-of-love/', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(29, 12, 11, 1, '2016-04-17', 0, '19:00:00', '2016-04-17', '', 'http://bostoncamerata.org/tickets.html', '', '', 'Another astonishing music-theater production by Artistic Director Anne Azéma. Based on an authentic, colorful narrative of festivity, tournaments, and love games in a medieval French castle, our performance captures the day’s celebrations through song and gesture. Daylight is the domain of men, who joust and fight in ritual encounters, as the women shout encouragement; when night falls, the women converse in music and dance, far from the masculine violence of the daytime. Mutual longing aroused during the day culminates in the evening’s rites, as the sexes come together in courtship, both playful and passionate. Camerata’s musicians are joined by graduate students from the Longy School of Music of Bard College in this beautiful and intense evocation of medieval desire.\r\n\r\nProduced in partnership with Longy School of Music of Bard College.', 0, 'active', 'http://bostoncamerata.org/blog/programs/the-nights-tale-a-tournament-of-love/', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(30, 13, 23, 1, '2016-05-22', 0, '15:00:00', '2016-05-22', '', 'http://bostoncamerata.org/tickets.html', '6174825800', '', 'Camerata''s pioneering exploration of folk hymnody in the young Republic includes spiritual songs, hymns, and anthems in a vigorous and authentic homegrown manner. This style, recalling many elements of European early music, grew up in the singing schools of colonial New England, travelled South and West in the 19th century, and continues to live on thanks to a new generation of motivated singers in all parts of the country. This collaboration with the newly-renovated Cathedral Church of St. Paul includes singers from local parish choirs.', 2662, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(31, 11, 4, 2, '2015-12-20', 0, '15:00:00', '2015-12-20', '$25', 'http://unioncollegeconcerts.org/collections/concerts/products/boston-camerata-12-20-15', '', '', 'The Christmas narrative retold using songs, chants, and instrumental pieces from the countries of the Mediterranean basin: Spain, Italy, and southern France, as well as north Africa and the Holy Land.  Works are drawn from medieval manuscripts and more recent, though still archaic, folklore and oral traditions. With voices, early instruments of Europe and the Middle East, and readings of the Christmas story. Camerata is joined by SHARQ Arabic Ensemble.\r\n\r\nAnne Azéma - voice, hurdy-gurdy &amp; director\r\nCamila Parias - voice\r\nDeborah Rentz-Moore - voice\r\nSteven Lundahl - brass, recorder\r\nKarim Nagi - percussion, voice\r\nBoujemaa Ragui - oud, ney, voice, percussion\r\nMehmet Sanlikol - voice, oud\r\nBeth Bahia Cohen - vielle', 2979, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(32, 14, 24, 1, '2016-10-22', 0, '20:00:00', '2016-10-22', '$25/40/55', 'http://bostoncamerata.org/blog/tickets/', '6172622092', '', '<img src=''/blog/images/cityOfFools.jpg'' class="alignleft" width=''20%''>Shortly before an important American election, this new program of songs and poems from the Middle Ages evokes the age-old themes of justice and corruption in the public sphere. Minstrel songs from medieval France, Provençe, and Germany, amazingly contemporary in their language, provide an amusing and sharply-etched perspective on our current  travails. Includes pungent selections from the Play of Daniel, Carmina Burana, and Roman de Fauvel; works by gifted musican-poets Philippe le Chancelier, Bertran de Born, and Thibault de Champagne; and a very American ending.\r\n\r\nAnne Azéma, director, voice, hurdy-gurdy; Jordan Weatherston Pitts voice; Christa Patton, winds, harp; Shira Kammen, vielle, harp; Joel Cohen, narrator, lauta; with young professionals from the Longy School of Music of Bard College.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(33, 15, 5, 1, '2016-12-02', 0, '20:00:00', '2016-12-02', '$25/40/55', 'http://bostoncamerata.org/blog/tickets/', '6172622092', '', '<img src=''/blog/images/puerNatusEst.jpg'' class="alignleft" width=''20%''>A glimpse of Christmas spirituality from Medieval France, Italy, England, and Provence, including music of the church and songs of private devotion around the joyous theme of the Nativity.  Included are songs to the Virgin Mary, processionals from Saint Martial of Limoges, hymns, lyrics, and miracle ballads sung in Latin, Old French, Old Provençal, and Saxon, interlaced with Medieval English texts of the Nativity. Our cast features an extraordinary trio of women''s voices with harp and vielle.\r\n\r\nAnne Azéma, Camila Parias, Deborah Rentz-Moore, voices; Christa Patton, winds, harp; Jacob Mariani, vielle.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(34, 15, 6, 1, '2016-12-03', 0, '20:00:00', '2016-12-03', '$25/40/55', 'http://bostoncamerata.org/blog/tickets/', '6172622092', '', 'A glimpse of Christmas spirituality from Medieval France, Italy, England, and Provence, including music of the church and songs of private devotion around the joyous theme of the Nativity.  Included are songs to the Virgin Mary, processionals from Saint Martial of Limoges, hymns, lyrics, and miracle ballads sung in Latin, Old French, Old Provençal, and Saxon, interlaced with Medieval English texts of the Nativity. Our cast features an extraordinary trio of women''s voices with harp and vielle.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(35, 15, 25, 1, '2016-12-04', 0, '15:00:00', '2016-12-04', '$25/40/55', '', '6175361970', '', 'A glimpse of Christmas spirituality from Medieval France, Italy, England, and Provence, including music of the church and songs of private devotion around the joyous theme of the Nativity.  Included are songs to the Virgin Mary, processionals from Saint Martial of Limoges, hymns, lyrics, and miracle ballads sung in Latin, Old French, Old Provençal, and Saxon, interlaced with Medieval English texts of the Nativity. Our cast features an extraordinary trio of women''s voices with harp and vielle.', 0, 'soldout', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(36, 16, 1, 1, '2016-12-19', 0, '20:00:00', '2016-12-19', '$25/40/55', 'http://bostoncamerata.org/blog/tickets/', '6172622092', '', '<img src=''/blog/images/inDulceJublio.jpg'' class="alignleft" width=''20%''>In the European North, the forests are deep; the nights are dark and long. Perhaps this is why, in reaction, the early Christmas music of the German-speaking peoples is so intensely joyful, so profoundly rich. Our program explores the marvelous music of German Christmas festivity through chants and chorales, simple carols, grandiose polyphony, and instrumental fantasias of the 15th to early 17th centuries. This new program will feature the stellar Boston Camerata Wind Ensemble and an expanded consort of voices and early instruments. \r\nAnne Azéma, Daniel Hershey, Camila Parias, Deborah Rentz-Moore, John Taylor Ward, voices; Brian Kay, Steven Lundahl, Liza Malamut, sackbuts;   Nathaniel Cox, cornetto, theorbo; Carol Lewis, viola da gamba.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(37, 1, 2, 1, '2017-01-29', 0, '15:00:00', '2017-01-29', '$25/40/55', 'http://bostoncamerata.org/blog/tickets/', '6172622092', '', '<img src=''/blog/images/daniel.jpg'' class="alignleft" width=''20%''>This powerful, highly-praised production returns to Boston in 2017 as part of a national tour. The themes of justice, and of truth spoken to power, are once again front and center as the Jewish captive Daniel confronts the tyrannical Belshazzar. The magnificent musical play of Daniel, composed eight centuries ago in Beauvais, France was newly transcribed from the original manuscript source  and powerfully staged for modern audiences by Anne Azéma, it was premiered in Boston in 2014 to critical and public acclaim. Presented in collaboration with Trinity Church; with the Trinity Choristers, Boston City Singers, and Longy School of Music of Bard College.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(38, 17, 26, 1, '2017-03-25', 0, '19:30:00', '2017-03-25', '$25/40/55', 'http://bostoncamerata.org/blog/tickets/treasures-of-devotion', '6172622092', '', '<img src=''/blog/images/treasuresOfDevotion.jpg'' class="alignleft" width=''20%''>Music of personal devotion from the early Renaissance, reflecting the spirituality of homes, family circles, and small chapels in an age of intense religious renewal. Prayers, songs, chants, including music for the Virgin, meditations on the cross, and astonishing reworkings of the day''s popular melodies to sacred texts by Josquin, Agricola, Compère, Senfl, Clemens non Papa, and others. Presented in collaboration with Boston University.  Anne Azéma, director, voice; Michael Barrett, voice, lute; Daniel Hershey, voice; Joel Frederiksen, voice, lute; Shira Kammen, vielle, harp; Andrew Arceci and Carol Lewis, violas da gamba.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(39, 14, 24, 1, '2016-10-22', 0, '20:00:00', '2016-10-22', '', '', '', '', '', 0, 'deleted', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(40, 4, 24, 1, '2016-12-02', 0, '20:00:00', '2016-12-02', '', '', '', '', '', 0, 'deleted', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(41, 18, 27, 2, '2016-09-09', 0, '20:00:00', '2016-09-09', '', '', '', '', 'Boston Camerata presents Roman de Fauvel for "Via Mediæval - Musik und Räume des Mittelalters". Jean Lorrain, narrator, voice; Anne Azéma, voice, hurdy-gurdy (Fortune); Tim Evans, voice (Fauvel); Joel Cohen, lauta, voice; Shira Kammen, vielle, harp, voice', 0, 'active', 'http://www.kultursommer.de/erleben/suche/Search_Evententry__id:3248/Mode_Search_Evententry__id:equal/detailClicked:1', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(42, 18, 8, 2, '2016-09-10', 0, '20:30:00', '2016-09-10', '', '', '', '', 'Boston Camerata presents Roman de Fauvel for "Festival Voix et Route Romane". Jean Lorrain, narrator, voice; Anne Azéma, voice, hurdy-gurdy (Fortune); Tim Evans, voice (Fauvel); Joel Cohen, lauta, voice; Shira Kammen, vielle, harp, voice', 0, 'active', 'http://www.voix-romane.com/', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(43, 16, 4, 2, '2016-12-18', 0, '15:00:00', '2016-12-18', '$30', 'http://unioncollegeconcerts.org/collections/concerts/products/boston-camerata-12-18-16', '', '', 'In the European North, the forests are deep; the nights are dark and long. Perhaps this is why, in reaction, the early Christmas music of the German-speaking peoples is so intensely joyful, so profoundly rich. Our program explores the marvelous music of German Christmas festivity through chants and chorales, simple carols, grandiose polyphony, and instrumental fantasias of the 15th to early 17th centuries. This new program will feature the stellar Boston Camerata Wind Ensemble and an expanded consort of voices and early instruments. \r\nAnne Azéma, Daniel Hershey, Camila Parias, Deborah Rentz-Moore, John Taylor Ward, voices; Brian Kay, Steven Lundahl, Liza Malamut, sackbuts;   Nathaniel Cox, cornetto, theorbo; Carol Lewis, viola da gamba.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(44, 1, 28, 2, '2017-01-26', 0, '17:00:00', '2017-01-26', '', '', '', '', 'This powerful, highly-praised production returns to Boston in 2017 as part of a national tour. The themes of justice, and of truth spoken to power, are once again front and center as the Jewish captive Daniel confronts the tyrannical Belshazzar. The magnificent musical play of Daniel, composed eight centuries ago in Beauvais, France was newly transcribed from the original manuscript source  and powerfully staged for modern audiences by Anne Azéma, it was premiered in Boston in 2014 to critical and public acclaim.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(45, 1, 29, 2, '2017-01-31', 0, '20:00:00', '2017-01-31', '', 'http://www.cathedralconcerts.org/product-category/concert-tickets/', '', '', 'This powerful, highly-praised production returns to Boston in 2017 as part of a national tour. The themes of justice, and of truth spoken to power, are once again front and center as the Jewish captive Daniel confronts the tyrannical Belshazzar. The magnificent musical play of Daniel, composed eight centuries ago in Beauvais, France was newly transcribed from the original manuscript source and powerfully staged for modern audiences by Anne Azéma, it was premiered in Boston in 2014 to critical and public acclaim. Presented in collaboration with Trinity Church; with the Trinity Choristers, Boston City Singers, and Longy School of Music of Bard College.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(46, 17, 30, 2, '2017-01-14', 0, '20:00:00', '2017-01-14', '', 'https://www.ago.net/the-boston-camerata-treasures-of-devotion', '', '', 'Music of personal devotion from the early Renaissance, reflecting the spirituality of homes, family circles, and small chapels in an age of intense religious renewal. Prayers, songs, chants, including music for the Virgin, meditations on the cross, and astonishing reworkings of the day’s popular melodies to sacred texts by Josquin, Agricola, Compère, Senfl, Clemens non Papa, and others. Anne Azéma, Michael Barrett, Daniel Hershey, Joel Frederiksen, voices; Andrew Arceci, Shira Kammen, Carol Lewis, viola da gamba.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(47, 17, 7, 2, '2017-03-26', 0, '13:00:00', '2017-03-26', '', 'http://www.metmuseum.org/events/programs/met-live-arts/anne-azema-fy17-1', '', '', 'Music of personal devotion from the early Renaissance, reflecting the spirituality of homes, family circles, and small chapels in an age of intense religious renewal. Prayers, songs, chants, including music for the Virgin, meditations on the cross, and astonishing reworkings of the day’s popular melodies to sacred texts by Josquin, Agricola, Compère, Senfl, Clemens non Papa, and others. Anne Azéma, director, voice; Michael Barrett, voice, lute; Daniel Hershey, voice; Joel Frederiksen, voice, lute; Shira Kammen, vielle, harp; Andrew Arceci and Carol Lewis, violas da gamba.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(48, 6, 31, 2, '2016-07-23', 0, '15:00:00', '2016-07-23', '', '', '', '', 'The Camerata presents our beloved interfaith program "The Sacred Bridge" at the Festival de Música Barroca de Alcântara. Experience the connections of Jewish, Muslim, and Christian music and spirituality of medieval Europe.\r\nAnne Azéma, voice, director; Joel Cohen, lauta, voice; Boujemaa Razgui, ney, oud, voice.', 0, 'active', 'http://festivaldealcantara.org/', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(49, 6, 32, 2, '2016-07-23', 0, '20:00:00', '2016-07-23', '', '', '', '', 'The Camerata presents our beloved interfaith program "The Sacred Bridge" at the Festival de Música Barroca de Alcântara. Experience the connections of Jewish, Muslim, and Christian music and spirituality of medieval Europe.\r\nAnne Azéma, voice, director; Joel Cohen, lauta, voice; Boujemaa Razgui, ney, oud, voice.', 0, 'active', 'http://festivaldealcantara.org/', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(50, 6, 33, 2, '2016-07-25', 0, '20:00:00', '2016-07-25', '', '', '', '', 'The Camerata presents our beloved interfaith program "The Sacred Bridge" at the Festival de Música Barroca de Alcântara. Experience the connections of Jewish, Muslim, and Christian music and spirituality of medieval Europe.\r\nAnne Azéma, voice, director; Joel Cohen, lauta, voice; Boujemaa Razgui, ney, oud, voice.', 0, 'active', 'http://festivaldealcantara.org/', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(51, 4, 34, 2, '2016-12-09', 0, '19:30:00', '2016-12-09', '', 'http://www.sdems.org/', '', '', 'A glimpse of Christmas spirituality from Medieval France, Italy, England, and Provence, including music of the church and songs of private devotion around the joyous theme of the Nativity. Included are songs to the Virgin Mary, processionals from Saint Martial of Limoges, hymns, lyrics, and miracle ballads sung in Latin, Old French, Old Provençal, and Saxon, interlaced with Medieval English texts of the Nativity. Our cast features an extraordinary trio of women’s voices with harp and vielle.\r\n\r\nPresented by San Diego Early Music Society.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(52, 4, 35, 2, '2016-12-11', 0, '15:00:00', '2016-12-11', '', 'https://dacamera.org/', '', '', 'A glimpse of Christmas spirituality from Medieval France, Italy, England, and Provence, including music of the church and songs of private devotion around the joyous theme of the Nativity. Included are songs to the Virgin Mary, processionals from Saint Martial of Limoges, hymns, lyrics, and miracle ballads sung in Latin, Old French, Old Provençal, and Saxon, interlaced with Medieval English texts of the Nativity. Our cast features an extraordinary trio of women’s voices with harp and vielle. \r\n\r\nPresented by the Da Camera Society. Two performance times will be announced soon.', 0, 'deleted', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(53, 19, 36, 0, '2016-10-29', 0, '11:30:00', '2016-10-29', '', 'http://www.gardnermuseum.org/calendar/events/7384', '6174366370', '', 'Anne Azéma, Artistic Director, will surprise visitors to the Isabella Stewart Gardner Museum with impromptu renditions of vocal music from Dante''s time, including songs the great poet himself might have heard in the palaces of fourteenth-century Florence.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(54, 4, 35, 2, '2016-12-11', 0, '14:00:00', '2016-12-11', '', 'http://dacamera.org/', '', '', 'A glimpse of Christmas spirituality from Medieval France, Italy, England, and Provence, including music of the church and songs of private devotion around the joyous theme of the Nativity. Included are songs to the Virgin Mary, processionals from Saint Martial of Limoges, hymns, lyrics, and miracle ballads sung in Latin, Old French, Old Provençal, and Saxon, interlaced with Medieval English texts of the Nativity. Our cast features an extraordinary trio of women’s voices with harp and vielle.\r\n\r\nPresented by the Da Camera Society.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(55, 4, 35, 2, '2016-12-11', 0, '16:30:00', '2016-12-11', '', 'http://dacamera.org/', '', '', 'A glimpse of Christmas spirituality from Medieval France, Italy, England, and Provence, including music of the church and songs of private devotion around the joyous theme of the Nativity. Included are songs to the Virgin Mary, processionals from Saint Martial of Limoges, hymns, lyrics, and miracle ballads sung in Latin, Old French, Old Provençal, and Saxon, interlaced with Medieval English texts of the Nativity. Our cast features an extraordinary trio of women’s voices with harp and vielle.\r\n\r\nPresented by the Da Camera Society.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(56, 17, 30, 2, '2017-01-15', 0, '19:00:00', '2017-01-15', '', 'https://www.ago.net/the-boston-camerata-treasures-of-devotion', '', '', 'Music of personal devotion from the early Renaissance, reflecting the spirituality of homes, family circles, and small chapels in an age of intense religious renewal. Prayers, songs, chants, including music for the Virgin, meditations on the cross, and astonishing reworkings of the day’s popular melodies to sacred texts by Josquin, Agricola, Compère, Senfl, Clemens non Papa, and others.  Anne Azéma, Michael Barrett, Daniel Hershey, Joel Frederiksenvoices; Andrew Arceci, Shira Kammen, Carol Lewis, viola da gamba', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(57, 20, 37, 1, '2017-07-08', 0, '20:00:00', '2017-07-08', '', 'http://tickets.rockportmusic.org/single/SelectSeating.aspx?p=4361', '', '', '<img src="/blog/images/lnlssampler.jpg" class="alignleft" width="20%">Rockport Chamber Music Festival presents Camerata''s groundbreaking telling of the Tristan and Iseult legend. Based on the original 12th-century sources, this medieval romance with narration weaves original elements together with staging and light for a truly unique concert experience.\r\n<p>\r\nAnne Azéma as Iseult<br>Sumner Thompson as Tristan<br>Clare McNamara as Brangane<br>Jason McStoots as Mark<br>Joel Cohen as the Narrator<br>with Susanne Ansorg, vielle<br> lighting design by Peter Torpey.', 0, 'active', 'http://rockportmusic.org/boston-camerata/', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(58, 21, 38, 2, '2017-07-29', 0, '14:00:00', '2017-07-29', '', 'www.bostoncamerata.org/tickets.html', '', '', '<img src="/blog/images/tristan.gif" class="alignleft" width="20%">We offer a summer buffet of music for our Maine friends, plus a sneak preview of our 2017-18 season! An opening set of love songs, chants, and spirituals from medieval France is followed by a feast of home-cooked ballads, Revolutionary partsongs, and paeans to American heroes, including pieces from the earliest Maine songbooks. Anne Azéma, director, voice; Michael Barrett, Daniel Hershey, Camila Parias, Deborah Rentz-Moore, Donald Wilkinson, voices; Joel Cohen, voice, guitar.', 0, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(59, 11, 39, 1, '2017-12-01', 0, '20:00:00', '2017-12-01', '', '/blog/tickets', '', '', '<img src="/blog/images/medXmas.jpg" class="alignleft" width="20%">The Christmas narrative retold using songs, chants, and instrumental pieces from the countries of the Mediterranean basin: Spain, Italy, southern France, North Africa and the Holy Land.  Works are drawn from medieval manuscripts and oral traditions. With voices, early instruments of Europe and the Middle East, and readings of the Christmas story. With SHARQ Arabic Ensemble.', 3532, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(60, 11, 40, 1, '2017-12-02', 0, '20:00:00', '2017-12-02', '', '/blog/tickets', '', '', '<img src="/blog/images/medXmas.jpg" class="alignleft" width="20%">\r\nThe Christmas narrative retold using songs, chants, and instrumental pieces from the countries of the Mediterranean basin: Spain, Italy, southern France, North Africa and the Holy Land.  Works are drawn from medieval manuscripts and oral traditions. With voices, early instruments of Europe and the Middle East, and readings of the Christmas story. With SHARQ Arabic Ensemble.', 3533, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(61, 11, 6, 1, '2017-12-03', 0, '15:00:00', '2017-12-03', '', '/blog/tickets', '', '', '<img src="/blog/images/medXmas.jpg" class="alignleft" width="20%">\r\nThe Christmas narrative retold using songs, chants, and instrumental pieces from the countries of the Mediterranean basin: Spain, Italy, southern France, North Africa and the Holy Land.  Works are drawn from medieval manuscripts and oral traditions. With voices, early instruments of Europe and the Middle East, and readings of the Christmas story. With SHARQ Arabic Ensemble.', 3534, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(62, 22, 41, 1, '2017-10-29', 0, '16:00:00', '2017-10-29', '', '/blog/tickets', '', '', '<img src="/blog/images/Patriots.jpg" class="alignleft" width="20%">Partsongs, marches, anthems, jigs, and ballads from the young Republic, when citizens sang their rejection of tyranny!  Rousing works by citizen-composers such as Boston tanner William Billings and Vermont tavern-keeper Jeremiah Ingalls still ring true today. With The Choral Fellows of Harvard University (Edward Jones, director) and young professionals from Longy School of Music of Bard College.', 3535, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(63, 23, 1, 1, '2017-12-18', 0, '20:00:00', '2017-12-18', '', '/blog/tickets', '', '', '', 3536, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(64, 24, 11, 1, '2018-04-21', 0, '20:00:00', '2018-04-21', '', '/blog/tickets', '', '', 'Performed by a stellar cast of singers and instrumentalists: Azéma, Thompson, McStoots, McNamara, Kammen, and Cohen, with young professionals from Longy School of Music of Bard College.', 3537, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(65, 24, 11, 1, '2018-04-22', 0, '16:00:00', '2018-04-22', '', '/blog/tickets', '', '', 'Performed by a stellar cast of singers and instrumentalists: Azéma, Thompson, McStoots, McNamara, Kammen, and Cohen, with young professionals from Longy School of Music of Bard College.', 3538, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(66, 25, 42, 2, '2017-08-25', 0, '20:15:00', '2017-08-25', '', 'http://www.festtage-basel.ch/festtage-2017.html', '', '', 'The Boston Camerata makes its long awaited debut in Switzerland. Anne Azéma and her colleagues will open the Basel Early Music Festival with a newly commissioned program of songs from the Middle Ages, exploring the themes of sleep and dreams, including works by the visionary Hildegard of Bingen.', 3539, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(67, 25, 42, 2, '2017-08-25', 0, '20:15:00', '2017-08-25', '', '', '', '', '', 3540, 'deleted', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(68, 11, 43, 2, '2017-12-10', 0, '17:00:00', '2017-12-10', '', '', '', '', '<img src="/blog/images/medXmas.jpg" class="alignleft" width="20%">The Christmas narrative retold using songs, chants, and instrumental pieces from the countries of the Mediterranean basin: Spain, Italy, southern France, North Africa and the Holy Land.  Works are drawn from medieval manuscripts and oral traditions. With voices, early instruments of Europe and the Middle East, and readings of the Christmas story. With SHARQ Arabic Ensemble.', 3541, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(69, 11, 43, 2, '2017-12-09', 0, '15:00:00', '2017-12-09', '', '', '', '', '<img src="/blog/images/medXmas.jpg" class="alignleft" width="20%">The Christmas narrative retold using songs, chants, and instrumental pieces from the countries of the Mediterranean basin: Spain, Italy, southern France, North Africa and the Holy Land.  Works are drawn from medieval manuscripts and oral traditions. With voices, early instruments of Europe and the Middle East, and readings of the Christmas story. With SHARQ Arabic Ensemble.', 3542, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(70, 11, 44, 2, '2017-12-12', 0, '19:30:00', '2017-12-12', '', 'https://www.mbam.qc.ca/calendrier/en/', '', '', '<img src="/blog/images/medXmas.jpg" class="alignleft" width="20%">', 3543, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(71, 1, 45, 2, '2018-01-19', 0, '19:30:00', '2018-01-19', '', 'http://www.chambermusic.org/', '', '', '', 3544, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(72, 1, 46, 2, '2018-01-21', 0, '14:00:00', '2018-01-21', '', 'https://chicagopresents.uchicago.edu/', '', '', '', 3545, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `ghs_gigpress_shows` VALUES(73, 23, 4, 2, '2017-12-17', 0, '15:00:00', '2017-12-17', '', 'https://unioncollegeconcerts.org/', '', '', '', 3546, 'active', '', 0, NULL, NULL, NULL, NULL, NULL, NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `ghs_gigpress_shows`
--
ALTER TABLE `ghs_gigpress_shows`
  ADD PRIMARY KEY (`show_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `ghs_gigpress_shows`
--
ALTER TABLE `ghs_gigpress_shows`
  MODIFY `show_id` int(4) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=74;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
